INSERT INTO questions (question_text, question_status,category_id, subcategory_id) VALUES 
(' Különbség az eljárás-orientált, procedurális és OOP nyelvek között','ACCEPTED',1,1),
('Absztrakció','ACCEPTED',1,1),
('Megkülönböztetés','ACCEPTED',1,1),
('Osztályozás','ACCEPTED',1,1),
('Általánosítás, specializálás','ACCEPTED',1,1),
('OOP program főbb jellemzői','ACCEPTED',1,1),
('Osztály fogalma, létrehozása és tervezése','ACCEPTED',1,1),
('Objektumpéldány létrehozása és szerepe','ACCEPTED',1,1),
('Az Object osztály mindenkinek az őse','ACCEPTED',1,1),
('Wrapper osztályok szerepe','ACCEPTED',1,1),
('A "super" kulcsszó használata','ACCEPTED',1,1),
('Az "extends" kulcsszó használata','ACCEPTED',1,1),
('Az "implements" kulcsszó használata','ACCEPTED',1,1),
('A POJO (Plain Old Java Object) szerepe','ACCEPTED',1,1),
('Egységbezárás fogalma','ACCEPTED',1,1),
('Információrejtés lényege','ACCEPTED',1,1),
('Öröklődés folyamata és példa','ACCEPTED',1,1),
('Polimorfizmus lényege és példa','ACCEPTED',1,1),
('Konstruktor szerepe','ACCEPTED',1,1),
('Konstruktor létrehozásának szabályai','ACCEPTED',1,1),
('Konstruktor túlterhelése','ACCEPTED',1,1),
('Destruktor szerepe (Java-ban nincs)','ACCEPTED',1,1),
('Garbage Collector működése','ACCEPTED',1,1),
('Láthatósági szintek: private, protected, public','ACCEPTED',1,1),
('Nem látható mező elérése','ACCEPTED',1,1),
('"static" kulcsszó jelentése','ACCEPTED',1,1),
('"final" kulcsszó használata','ACCEPTED',1,1),
('"this" kulcsszó használata','ACCEPTED',1,1),
('Mező fogalma egy osztálynál','ACCEPTED',1,1),
('Property fogalma osztályok esetében','ACCEPTED',1,1),
('Getterek és setterek használata','ACCEPTED',1,1),
('Konvenciók a konstruktorok, getterek, setterek, mezők elhelyezése','ACCEPTED',1,1),
('Többszörös öröklődés Javában','ACCEPTED',1,1),
('Java SE rövidítése, használata és részei','ACCEPTED',1,2),
('Java EE rövidítése, használata és részei','ACCEPTED',1,2),
('JDK részei','ACCEPTED',1,2),
('JRE használata','ACCEPTED',1,2),
('JVM működése','ACCEPTED',1,2),
('"javac" művelete','ACCEPTED',1,2),
('JIT szerepe','ACCEPTED',1,2),
('Java kódok fordítása','ACCEPTED',1,2),
('"java.io" csomag használata','ACCEPTED',1,2),
('"java.sql" csomag használata','ACCEPTED',1,2),
('"java.awt" csomag használata','ACCEPTED',1,2),
('"java.math" csomag használata','ACCEPTED',1,2),
('"java.beans" csomag használata','ACCEPTED',1,2),
('"java.util" csomag használata','ACCEPTED',1,2),
('Math osztály fontosabb metódusai','ACCEPTED',1,2),
('Primitív típusok és jellemzőik','ACCEPTED',1,2),
('Összetett típusok Java-ban','ACCEPTED',1,2),
('Matematikai operátorok','ACCEPTED',1,2),
('Relációs operátorok','ACCEPTED',1,2),
('Logikai operátorok','ACCEPTED',1,2),
('Prefix és postfix értéknövelés és értékcsökkentés','ACCEPTED',1,2),
('Scanner vs. BufferedReader különbsége','ACCEPTED',1,2),
('Adatok átalakítása String típusba','ACCEPTED',1,2),
('Java erősen típusos nyelv','ACCEPTED',1,2),
('Változó létrehozásának szempontjai','ACCEPTED',1,2),
('Switch-case szerkezet használata','ACCEPTED',1,2),
('"default" a switch-case szerkezetben','ACCEPTED',1,2),
('"break" a switch-case szerkezetben','ACCEPTED',1,2),
('"break" és "continue" használata','ACCEPTED',1,2),
('Ciklusok Java-ban','ACCEPTED',1,2),
('Elágazások Java-ban','ACCEPTED',1,2),
('While vs. Do-While különbsége','ACCEPTED',1,2),
('Programozási tételek és használatuk','ACCEPTED',1,2),
('"void" kulcsszó használata','ACCEPTED',1,2),
('Metódus formális és aktuális paramétere','ACCEPTED',1,2),
('Metódus túlterhelés létrehozása','ACCEPTED',1,2),
('Metódus szignatúrája','ACCEPTED',1,2),
('Metódus deklaráció és hívás közötti különbség','ACCEPTED',1,2),
('Tömbök használata és jellemzői','ACCEPTED',1,2),
('Tömbök eleminek hivatkozása','ACCEPTED',1,2),
('Tömbkezelő metódusok','ACCEPTED',1,2),
('Milyen rendező algoritmusokat ismersz?','ACCEPTED',1,2),
('Melyek azok a tényezők, amelyek meghatározzák egy rendező algoritmus jóságát?','ACCEPTED',1,2),
('Hogyan hozunk létre fájlt?','ACCEPTED',1,2),
('Miért fontos, hogy lezárjuk a fájlt a használat után?','ACCEPTED',1,2),
('Hogyan olvasunk fájlból?','ACCEPTED',1,2),
('Vannak –e pointerek javaban?','ACCEPTED',1,2),
('Mire használható a split függvény? Mi a visszatérése?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk szöveg darabolására?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk szöveg összefűzésére?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk formázására?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk részszövegképzésre?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk tartalmazás vizsgálatra?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk egyenlőség vizsgálatra?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk karakterek cseréjére?','ACCEPTED',1,2),
('Melyik szövegkezelő metódust használhatjuk keresésre?','ACCEPTED',1,2),
('Melyik osztályt érdemes dátumkezelésre használni Java 11-ben? Melyik package-ben található?','ACCEPTED',1,2),
('Melyek a Java 11-ben már elavult (deprecated) osztályok dátum és időkezelésre?','ACCEPTED',1,2),
('Hogyan működik a dátumok összehasonlítása?','ACCEPTED',1,2),
('Sorolj fel néhány rekurzióval megoldható feladatot!','ACCEPTED',1,2),
('Milyen jellemzői vannak a rekurzív algoritmusoknak?','ACCEPTED',1,2),
('Melyek a Java LTS verziói?','ACCEPTED',1,2),
('Melyek a Java 8-as verziójának újdonságai?','ACCEPTED',1,2),
('Melyek a Java 11-es verziójának újdonságai?','ACCEPTED',1,2),
('Melyek a Java 17-es verziójának újdonságai?','ACCEPTED',1,2),
('Miért hasznos a Java Collection Framework (JCF)?','ACCEPTED',1,3),
('JCF-en belül milyen interface-ket és azon belül milyen osztályokat ismersz?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak a List interfésznek?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak a Set interfésznek?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak a Map interfésznek?','ACCEPTED',1,3),
('Milyen osztályok szerepelnek a List interface-n belül?','ACCEPTED',1,3),
('Milyen osztályok szerepelnek a Set interface-n belül?','ACCEPTED',1,3),
('Milyen osztályok szerepelnek a Map interface-n belül?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak az ArrayList osztálynak?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak a LinkedList osztálynak?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak a Stack osztálynak?','ACCEPTED',1,3),
('Mire használhatóak és milyen jellemzői vannak a Hashtable osztálynak?','ACCEPTED',1,3),
('Melyik listakezelő metódussal lehet index alapján eltávolítani egy elemet?','ACCEPTED',1,3),
('Melyik listakezelő metódussal lehet csökkenő sorrendbe rendezni?','ACCEPTED',1,3),
('Melyik listakezelő metódussal lehet növekvő sorrendbe rendezni?','ACCEPTED',1,3),
('Mi a különbség az ArrayList és a sima tömb használata között?','ACCEPTED',1,3),
('Milyen ArrayList-hez használható metódusokat ismersz?','ACCEPTED',1,3),
('Mi a különbség az interface-ek és az absztrakt osztályok használata között?','ACCEPTED',1,3),
('A Hashtable osztálynál miért nem működik a for ciklus?','ACCEPTED',1,3),
('Mire használjuk az interface-eket, jellemezzük a működésüket!','ACCEPTED',1,3),
('Miért hasznos az alkalmazás rétegezett felépítése?','ACCEPTED',1,3),
('Mire használható és hogyan működik az MVC tervezési minta?','ACCEPTED',1,3),
('Mire való a Model réteg az MVC esetében?','ACCEPTED',1,3),
('Mire való a View réteg az MVC esetében?','ACCEPTED',1,3),
('Mire való a Controller réteg az MVC esetében?','ACCEPTED',1,3),
('Hogyan működik az MVP tervezési minta?','ACCEPTED',1,3),
('Hogyan működik az MVVM tervezési minta?','ACCEPTED',1,3),
('Mire használjuk a DTO-kat?','ACCEPTED',1,3),
('Mire használjuk a DAO réteget?','ACCEPTED',1,3),
('Mire használható a service réteg?','ACCEPTED',1,3),
('Mire használható a repository réteg?','ACCEPTED',1,3),
('Melyek osztályokat használhatjuk reguláris kifejezések kezelésére?','ACCEPTED',1,3),
('Milyen speciális karakterek, beállítások szerepelhetnek a reguláris kifejezésekben?','ACCEPTED',1,3),
('Mire valók a kivételek?','ACCEPTED',1,3),
('Milyen kivételkezelő osztályokat ismersz?','ACCEPTED',1,3),
('Hogyan hozható létre saját kivételkezelő osztály?','ACCEPTED',1,3),
('Mi a különbség a checked és unchecked kivétel között?','ACCEPTED',1,3),
('Hogyan építsük fel a try-catch szerkezetünket?','ACCEPTED',1,3),
('Kivételkezelésnél mire való a finally kulcsszó?','ACCEPTED',1,3),
('Mire használhatóak a predicate-ek?','ACCEPTED',1,3),
('Mire használhatóak a functional interface-ek?','ACCEPTED',1,3),
('Melyek a lambda kifejezések használatának előnyei?','ACCEPTED',1,3),
('Milyen szintakszissal hozhatóak létre lambda kifejezések?','ACCEPTED',1,3),
('Mire használható a StreamAPI?','ACCEPTED',1,3),
('Milyen szintakszissal hozhatunk létre Stream API segítségével: a. iterációt? b. szűrést? csoportosítást? d. aggregált műveleteket? e. kimeneti darabszám korlátozást?','ACCEPTED',1,3),
('Melyik osztállyal hozhatunk létre szálakat?','ACCEPTED',1,3),
('Hogyan készíthetünk többszálú alkalmazást?','ACCEPTED',1,3),
('Mire való a synchronized kulcsszó?','ACCEPTED',1,3),
('Mire használható a start metódus a Thread osztálynál?','ACCEPTED',1,3),
('Mire használható a join metódus a Thread osztálynál?','ACCEPTED',1,3),
('Mire használható a sleep metódus a Thread osztályon?','ACCEPTED',1,3),
('Milyen megoldandó problémákat vet fel a többszálú alkalmazás készítése?','ACCEPTED',1,3),
('Mire használható az URL osztály?','ACCEPTED',1,3),
('Mi a különbség az XML és JSON között, melyiknek mik az előnyei/hátrányai?','ACCEPTED',1,3),
('Mire használható a Gson osztály?','ACCEPTED',1,3),
('Melyek a legfontosabb osztályok és metódusok egy XML állomány feldolgozásához?','ACCEPTED',1,3),
('Melyek a legfontosabb osztályok és metódusok egy JSON állomány feldolgozásához?','ACCEPTED',1,3),
('Mire használjuk a Timer és TimerTask osztályokat?','ACCEPTED',1,3),
('Milyen osztályokat és metódusokat tartalmaz a Reflection API?','ACCEPTED',1,3),
('Melyik osztályok a legfontosabb, leggyakrabban használt osztályok a java.sql csomagból?','ACCEPTED',1,4),
('Mire használható a Connection osztály?','ACCEPTED',1,4),
('Mire használható a Statement osztály?','ACCEPTED',1,4),
('Mire használható a DriverManager osztály?','ACCEPTED',1,4),
('Mire használható az SQLException osztály?','ACCEPTED',1,4),
('Melyek a Prepared Statement használatának előnyei?','ACCEPTED',1,4),
('Mire használjuk a ResultSet-et?','ACCEPTED',1,4),
('Hogyan tudunk a ResultSet indexei-re hivatkozni?','ACCEPTED',1,4),
('Mire való a JPA, hogyan működik?','ACCEPTED',1,4),
('Hogyan működik a Hibernate?','ACCEPTED',1,4),
('Mit jelent az, hogy egy alkalmazás esemény-vezérelt?','ACCEPTED',1,5),
('Milyen események lehetnek?','ACCEPTED',1,5),
('Hogyan csoportosíthatóak az események?','ACCEPTED',1,5),
('Swing-et, AWT-t vagy JavaFX-et érdemes használni? Miért?','ACCEPTED',1,5),
('Mit jelent Swing-nél a look-and-feel támogatás?','ACCEPTED',1,5),
('Hogyan hozhatunk létre Swing-es grafikus felületet?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni felugró ablakot?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni pipálható mezőt?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni rádió gombot?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni legördülő menüt?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni címkét?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni szöveges beviteli mezőt?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni jelszó típusú beviteli mezőt?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni gombot?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni tárolót?','ACCEPTED',1,5),
('Swingben, illetve JavaFX-ben melyik komponessel lehet létrehozni komponensek csoportosítását?','ACCEPTED',1,5),
('Hogyan hozhatunk létre JavaFX-es grafikus felületet?','ACCEPTED',1,5),
('Milyen layout-okat használhatunk Swingben?','ACCEPTED',1,5),
('Milyen layout-okat használhatunk JavaFX-ben?','ACCEPTED',1,5),
('Hogyan lehet egy komponens láthatóságát beállítani Swingben, illetve JavaFX-ben?','ACCEPTED',1,5),
('Hogyan lehet egy komponens elérhetőségét beállítani Swingben, illetve JavaFX-ben?','ACCEPTED',1,5),
('Melyek a Maven használatának előnyei?','ACCEPTED',1,6),
('Mire használjuk a pom.xml-t?','ACCEPTED',1,6),
('Milyen műveletek szerepelnek a Maven-es projekt életciklusában?','ACCEPTED',1,6),
('Mit csinálnak a következő műveletek: validate, compile, test, package, verify, install, deploy?','ACCEPTED',1,6),
('Hogyan adhatunk függőséget a projektünkhoz?','ACCEPTED',1,6),
('Melyik oldalról lehet dependenciát letölteni?','ACCEPTED',1,6),
('Mire használja a Maven a lokális repot?','ACCEPTED',1,6),
('Mi történik, ha a lokális repoban elérhető a pom.xml-ben hivatkozott dependencia?','ACCEPTED',1,6),
('Mire használjuk az artifactId-t?','ACCEPTED',1,6),
('Mire használjuk a groupId-t?','ACCEPTED',1,6),
('Hogyan működik a kliens-szerver kommunikáció?','ACCEPTED',1,7),
('Melyek a fontosabb HTTP portok?','ACCEPTED',1,7),
('Milyen HTTP status kódokat ismersz?','ACCEPTED',1,7),
('Melyik Java EE technológiák tartoznak a WebProfile-ba és melyikek a Full Platform-ba?','ACCEPTED',1,7),
('Mi az a SOAP?','ACCEPTED',1,7),
('Mire használhatóak a szervletek? Jellemezzük a működésüket!','ACCEPTED',1,7),
('Milyen alapértelmezett metódusai vannak a szervleteknek?','ACCEPTED',1,7),
('Mire használható a JSP technológia?','ACCEPTED',1,7),
('Mire való az include parancs a JSP-nél?','ACCEPTED',1,7),
('Milyen módszerrel telepíthetőek JAR fájlok (pl. MySQL connector)?','ACCEPTED',1,7),
('Mire használhatóak a bean-ek?','ACCEPTED',1,7),
('Mire használjuk a JSTL-t, milyen direktívák használhatóak?','ACCEPTED',1,7),
('Hogyan értelmezi a Spring Boot az MVC modelt?','ACCEPTED',1,7),
('Melyek a Spring Boot alkalmazás létrehozásának lehetőségei?','ACCEPTED',1,7),
('Melyek a fontosabb Spring Boot modulok és komponenseik?','ACCEPTED',1,7);
